// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "api-consumer-service/internal/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPostsDispatcher is an autogenerated mock type for the PostsDispatcher type
type MockPostsDispatcher struct {
	mock.Mock
}

type MockPostsDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostsDispatcher) EXPECT() *MockPostsDispatcher_Expecter {
	return &MockPostsDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, postChan
func (_m *MockPostsDispatcher) Dispatch(ctx context.Context, postChan <-chan []dto.Post) error {
	ret := _m.Called(ctx, postChan)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, <-chan []dto.Post) error); ok {
		r0 = rf(ctx, postChan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostsDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockPostsDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - postChan <-chan []dto.Post
func (_e *MockPostsDispatcher_Expecter) Dispatch(ctx interface{}, postChan interface{}) *MockPostsDispatcher_Dispatch_Call {
	return &MockPostsDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, postChan)}
}

func (_c *MockPostsDispatcher_Dispatch_Call) Run(run func(ctx context.Context, postChan <-chan []dto.Post)) *MockPostsDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(<-chan []dto.Post))
	})
	return _c
}

func (_c *MockPostsDispatcher_Dispatch_Call) Return(_a0 error) *MockPostsDispatcher_Dispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostsDispatcher_Dispatch_Call) RunAndReturn(run func(context.Context, <-chan []dto.Post) error) *MockPostsDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostsDispatcher creates a new instance of MockPostsDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostsDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostsDispatcher {
	mock := &MockPostsDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
